spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # Druid 数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置监控统计拦截的filters，去掉后，监控界面sql将无法统计，'wall'用于防火墙
    filters: stat, wall, log4j

    tomcat:
      # 初始化数量
      initial-size: 1
      # 最大活跃数
      max-active: 20
      # 最大连接等待超时时间60秒
      max-wait: 60000
      # 通过ConnectionProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mermsql=true;druid.stat.slowSqlMillis=5000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      # 上传单个文件最大容量
      max-file-size: 2MB
      # 批量上传文件最大容量
      max-request-size: 10MB

